const express = require("express");
const router = express.Router();
const userController = require("../controllers/userController");
router.post("/refresh", userController.refreshToken);
router.post("/register", userController.register);
router.post("/login", userController.login);
router.post("/logout", userController.logout);
router.get("/:email/profile", userController.getProfile);
router.put("/:email/profile", userController.updateProfile);
module.exports = router;
